main_menu = ('Главное меню. Выберете новую запись или зайдите в личный кабинет, '
             'чтобы просмотреть ваши прошлые записи.')
account_menu_button = 'Личный кабинет'
new_appointment_button = 'Новая запись'
back_button = 'Обратно в меню'
back_to_new_appointment_button = 'Обратно в новую запись'
account_menu = 'Личный кабинет. Просмотрите...'
new_appointment = 'Новая запись. Запишитесь...'
by_salon = 'Выбор по салону'
by_master = 'Выбор по мастеру'
by_service = 'Выбор по услуге'

by_salon_menu = 'Меню выбора по салону'
by_master_menu = 'Меню выбора по мастеру'
by_service_menu = 'Меню выбора по услуге'
date_menu = 'Меню выбора даты'
past_appointments = 'Прошлые записи'
my_appointments = 'Мои записи'
phone_request = 'Предоставьте свой номер телефона'
nearest_salon = 'Ближайший салон'
registration = 'Регистрация'
policy = 'Политика обработки данных'
policy_agree = 'Я даю согласие на обработку данных'
confirm = 'Подтвердить запись'
confirmed = 'Ваша запись подтверждена'

db_error_message = 'При выполнении запроса произошла ошибка. Пожалуйста, повторите операцию позже.'
