# Generated by Django 4.1.4 on 2022-12-08 15:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='providers', verbose_name='фото')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('city', models.CharField(default='Москва', max_length=50, verbose_name='город')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='широта')),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='цена')),
                ('provided_by', models.ManyToManyField(related_name='services', related_query_name='service', to='salons.provider', verbose_name='предоставляют мастера')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='день недели')),
                ('from_hour', models.TimeField(verbose_name='начало работы')),
                ('to_hour', models.TimeField(verbose_name='конец работы')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.provider', verbose_name='мастер')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.salon', verbose_name='салон')),
            ],
            options={
                'unique_together': {('provider', 'weekday')},
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='works_at',
            field=models.ManyToManyField(related_name='providers', related_query_name='provider', through='salons.ProviderSchedule', to='salons.salon', verbose_name='где работает'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('time', models.TimeField(verbose_name='время')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.customer', verbose_name='клиент')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.provider', verbose_name='мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.service', verbose_name='услуга')),
            ],
            options={
                'unique_together': {('provider', 'date', 'time')},
            },
        ),
    ]
