# Generated by Django 4.1.4 on 2022-12-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerschedule',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_timeslots', to='salons.provider', verbose_name='мастер'),
        ),
        migrations.AlterField(
            model_name='providerschedule',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_schedules', to='salons.salon', verbose_name='салон'),
        ),
    ]
