# Generated by Django 4.1.4 on 2022-12-08 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='дата и время')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.customer', verbose_name='клиент')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.provider', verbose_name='мастер')),
                ('salon', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='salons.salon', verbose_name='салон')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.service', verbose_name='услуга')),
            ],
            options={
                'unique_together': {('provider', 'date_time')},
            },
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
