# Generated by Django 4.1.4 on 2022-12-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_alter_appointment_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerschedule',
            name='from_hour',
            field=models.TimeField(help_text='Only exact hours with 00 minutes are allowed, e.g. 11:00, 14:00', verbose_name='начало работы'),
        ),
        migrations.AlterField(
            model_name='providerschedule',
            name='to_hour',
            field=models.TimeField(help_text='Only exact hours with 00 minutes are allowed, e.g. 11:00, 14:00', verbose_name='конец работы'),
        ),
    ]
