# Generated by Django 4.1.4 on 2022-12-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_alter_providerschedule_from_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerschedule',
            old_name='from_hour',
            new_name='time_from',
        ),
        migrations.RenameField(
            model_name='providerschedule',
            old_name='to_hour',
            new_name='time_till',
        ),
    ]
