# Generated by Django 4.1.4 on 2022-12-09 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_rename_from_hour_providerschedule_time_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='time_close',
            field=models.TimeField(default=datetime.time(21, 0), help_text='Only exact hours with 00 minutes are allowed, e.g. 11:00, 14:00', verbose_name='время закрытия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='time_open',
            field=models.TimeField(default=datetime.time(10, 0), help_text='Only exact hours with 00 minutes are allowed, e.g. 11:00, 14:00', verbose_name='время открытия'),
            preserve_default=False,
        ),
    ]
