# Generated by Django 4.1.4 on 2022-12-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_salon_time_close_salon_time_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время'),
        ),
    ]
