# Generated by Django 4.1.4 on 2022-12-09 16:49

import datetime

from django.db import migrations


def forwards(apps, schema_editor):
    Appointment = apps.get_model('salons', 'Appointment')
    for appt in Appointment.objects.all():
        appt.datetime = datetime.datetime.combine(
            appt.date, appt.time, tzinfo=datetime.timezone(datetime.timedelta(hours=3))
        )
        appt.save(update_fields=['datetime'])


def backwards(apps, schema_editor):
    Appointment = apps.get_model('salons', 'Appointment')
    for appt in Appointment.objects.all():
        appt.datetime = None
        appt.save(update_fields=['datetime'])
        appt.save(update_fields=['datetime'])


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_appointment_datetime'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
